spring:
  application:
    name: solarestimater

  # Profile specific properties
  profiles:
    active: dev

  # PostgreSQL Configuration
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # JPA/Hibernate Properties
  jpa:
    hibernate:
      ddl-auto: update
    # show-sql: true
    properties:
      hibernate:
        # format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect


inverter:
  url: api.shinemonitor.com/public/

company:
  key: MzmgRRw3VMZSLnQQ

# Logging Configuration
# logging:
#   level:
#     org:
#       hibernate:
#         SQL: DEBUG
#         type:
#           descriptor:
#             sql:
#               BasicBinder: TRACE

# JWT token
jwt:
  secret: 9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9
  expiration: 3600000

# actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,loggers,env"
  endpoint:
    health:
      show-details: always